import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Download, RotateCcw } from "lucide-react";
import { AgentConversation } from "./AgentConversation";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Lightbulb } from "lucide-react";

interface Message {
  id: string;
  agent: "researcher" | "critic" | "synthesizer";
  content: string;
  timestamp: string;
  responding_to?: string;
}

interface WorkflowResults {
  query: string;
  conversation_history: Array<{
    agent: string;
    role: string;
    message: string;
    responding_to?: string;
  }>;
  insight_report?: string;
  synthesis: string;
  follow_up_questions: string[];
}

interface ResultsViewProps {
  results: WorkflowResults | null;
  sessionTopic: string;
  sessionId: string;
  onNewAnalysis: () => void;
}

export const ResultsView = ({ results, sessionTopic, sessionId, onNewAnalysis }: ResultsViewProps) => {
  if (!results) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Research Results</CardTitle>
          <CardDescription>
            Run agent analysis to see results
          </CardDescription>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground">
            Start analysis in the "Agent Analysis" tab to generate insights
          </p>
        </CardContent>
      </Card>
    );
  }

  const handleDownloadReport = () => {
    // Build conversation section
    let conversationSection = "";
    if (results.conversation_history.length > 0) {
      conversationSection = "\n## Agent Conversation\n\n";
      results.conversation_history.forEach((msg) => {
        if (msg.responding_to) {
          conversationSection += `### ${msg.agent} (responding to ${msg.responding_to}):\n\n`;
        } else {
          conversationSection += `### ${msg.agent}:\n\n`;
        }
        conversationSection += `${msg.message}\n\n---\n\n`;
      });
    }

    // Build insight section
    let insightSection = "";
    if (results.insight_report) {
      insightSection = `\n## 🎯 Collective Insight Report\n\n${results.insight_report}\n\n---\n`;
    }

    const report = `# Research Analysis Report

## Query
${results.query}

## Session
${sessionTopic}

${insightSection}

${conversationSection}

## Follow-up Questions
${results.follow_up_questions.map(q => `- ${q}`).join('\n')}

## Synthesis
${results.synthesis}

---
Generated by Research Agent System
Session: ${sessionId}
`;

    const blob = new Blob([report], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "research_report.md";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Convert conversation history to messages format
  const messages: Message[] = results.conversation_history.map((msg, idx) => ({
    id: `msg-${idx}`,
    agent: msg.agent.toLowerCase() as "researcher" | "critic" | "synthesizer",
    content: msg.message,
    timestamp: new Date().toLocaleTimeString(),
    responding_to: msg.responding_to,
  }));

  return (
    <div className="space-y-6">
      {/* Collective Insight Report */}
      {results.insight_report && (
        <Alert className="border-agent-synthesizer bg-agent-synthesizer/5">
          <Lightbulb className="h-4 w-4" />
          <AlertTitle>Collective Insight Report</AlertTitle>
          <AlertDescription className="mt-2 whitespace-pre-wrap">
            {results.insight_report}
          </AlertDescription>
        </Alert>
      )}

      {/* Agent Conversation */}
      <Card>
        <CardHeader>
          <CardTitle>Agent Collaboration Flow</CardTitle>
          <CardDescription>
            Watch how agents challenge and respond to each other
          </CardDescription>
        </CardHeader>
        <CardContent>
          <AgentConversation messages={messages} />
        </CardContent>
      </Card>

      {/* Synthesis */}
      <Card>
        <CardHeader>
          <CardTitle>Synthesis</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm leading-relaxed whitespace-pre-wrap">{results.synthesis}</p>
        </CardContent>
      </Card>

      {/* Follow-up Questions */}
      {results.follow_up_questions.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Follow-up Research Questions</CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-2">
              {results.follow_up_questions.map((question, idx) => (
                <li key={idx} className="text-sm leading-relaxed">
                  • {question}
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      )}

      {/* Actions */}
      <div className="flex gap-4">
        <Button onClick={handleDownloadReport} variant="secondary" className="flex-1">
          <Download className="mr-2 h-4 w-4" />
          Download Report
        </Button>
        <Button onClick={onNewAnalysis} variant="outline" className="flex-1">
          <RotateCcw className="mr-2 h-4 w-4" />
          New Analysis
        </Button>
      </div>
    </div>
  );
};
